### ISSUE TITLE
Incorrect number of cells in stroma tissue category

### ISSUE THREAD

**Issue by rvanguri** [akoyabio/phenoptrReports#15] opened 2019-07-01 16:08 UTC
I am running the "Analyze consolidated data" app and I see that it does find any cells for a particular phenotype in the Stroma category. The Tumor tissue category calculates correctly though. I've tried variations where I try to calculate only in the Stroma, Tumor and Stroma and Tumor alone. The Tumor totals are always correct but Stroma always results in 0 cells. If I manually grep through the Consolidated_data.txt it is clear that there are cells in the Stroma tissue category that should get counted.

**Comment by AB-Kent** [comment] 2019-07-02 12:57
Hi, can you possibly send me the Consolidated_data.txt and Script.R files that show this problem? Thanks!

**Comment by rvanguri** [comment] 2019-07-02 14:11
Please see attached.
[phenoptr_issue.zip](https://github.com/akoyabio/phenoptrReports/files/3350452/phenoptr_issue.zip)

**Comment by AB-Kent** [comment] 2019-07-02 15:03
Thank you for the data! The problem is that a few of your cells do not have cytoplasm data. This caused the sum to be `NA` which was then mis-interpreted by the counting code.

A couple of solutions for you:
- I've checked in a fix which you can get by installing the dev version with `devtools::install_github('akoyabio/phenoptrReports@9000')`
- Modify your phenotype expression to check for NA values; the correct expression is
`` CD3+/~!is.na(`Cytoplasm CD8 (Opal 690) Mean`) & `Cytoplasm CD8 (Opal 690) Mean`>0.65``

Thanks again for the bug report and the data to repro!

**Closed as completed by AB-Kent** 2019-07-02 15:03 UTC

**Comment by rvanguri** [comment] 2019-07-02 15:58
This works perfectly now, thanks!
